logging.file: avaloq-jms.log

ibm.mq:
  queueManager: QM1
  channel: DEV.ADMIN.SVRCONN
  connName: 10.0.200.94(1414)
  user: mquser
  password: mquser

spring.main:
  banner-mode: "off"

com.agdelta:
  avaloq.jms.acknowledge.code: /acknowledge/msg/key_list/key/val